language: go

go:
  - 1.x

before_install:
  - wget --no-check-certificate https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
  - tar xvf glide-v0.12.3-linux-amd64.tar.gz
  - sudo mv linux-amd64/glide /usr/bin/

install: 
  - glide install

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
  